### ISSUE TITLE
Server Side Includes

### ISSUE THREAD

**Issue by pickettj** [pickettj/central_asia_gazetteer#20]
Investigate and implement a [server side includes](http://dh.obdurodon.org/ssi.html) solution to (for instance) the nav bar.

**Comment by pickettj** [comment]
I've gone through the steps in [the instructions](http://dh.obdurodon.org/ssi.html), but it resulted in an [error message and no menu bar](http://gazetteer.obdurodon.org/).

The [menu bar code is here](https://github.com/pickettj/central_asia_gazetteer/blob/master/website/menubar.xhtml); and the inserted code (`<!--#include virtual="menubar.html" -->`) can be found in the [website files](https://github.com/pickettj/central_asia_gazetteer/blob/master/website/index.xhtml).

Command prompt inputs were as follows:
```
[pickettj@obdurodon gazetteer]$ ls
about.xhtml  css  images  index.xhtml  java  menubar.xhtml
[pickettj@obdurodon gazetteer]$ chmod +x index.xhtml
[pickettj@obdurodon gazetteer]$ chmod +x about.xhtml
```
Help, @zme1 ?

**Comment by zme1** [comment]
@pickettj Check the file name, specifically the file extension (cough, cough) in your XHTML files and give it another go...

**Comment by pickettj** [comment]
Riiiight...

Problem solved.
