### ISSUE TITLE
How do I delete these old directories from the repo?

### ISSUE THREAD

**Issue by engeljonathan98** [pickettj/central_asia_gazetteer#22]
I've restructured the data per the directory structure we decided on a few weeks ago, but we made some folders that don't fit into that structure by mistake. The only folder on the top-level should be "rsrc" and all the other folders that exist right now should be nested w/n it.

I've already copied those folders into rsrc on my local machine and pushed that. It worked! However, the old folders and the data they contained still exist on this GitHub repo. How do I kill them?

**Comment by gabikeane** [comment]
Navigate to the top-level of the repository and delete the folders using 

```rm -r foldername```

This will recursively remove all the files and then remove the folder itself. Be very careful with the -r switch, it's powerful!

After you've made those changes, add, commit, and push the repo like normal. Those files will remain in the version history, so you'll always have a record of them there, but they're gone from current master after you push.

**Comment by engeljonathan98** [comment]
Thanks!
