### ISSUE TITLE
How do I do an SSI in an HTML file?

### ISSUE THREAD

**Issue by engeljonathan98** [pickettj/central_asia_gazetteer#36]
By the nature of Leaflet, any file which includes the map must be an .html, not a .xhtml. However, Obdurodon is not configured to automatically check .htmls for SSIs.

So: how do I do that?

**Comment by djbpitt** [comment]
@engeljonathan98 Sorry for the delay! Please try again.

**Comment by engeljonathan98** [comment]
No change. I am getting this error on map_test.html, which is uploaded to the server:

"[an error occurred while processing this directive]"

My statement reads like this:

`<!--#include virtual="rsrc\ssi\map_interface.html" -->`

**Comment by djbpitt** [comment]
@engeljonathan98 Er ... forward slashes ..

**Comment by engeljonathan98** [comment]
Jeez. Thanks, we're go.
