### ISSUE TITLE
Assess whether it makes sense to convert schema to a subset of TEI

### ISSUE THREAD

**Issue by pickettj** [pickettj/central_asia_gazetteer#7]
Examine draft custom schema, write into comments initial suggestions as to which TEI elements might take the place of the home-brewed ones.

**Comment by engeljonathan98** [comment]
Could you possibly provide an example of how the location elements were used to tag a different text you worked on? I think I get the schema but I would like to see it in use before I compare it to TEI.

If you don't have this, I can work w/ just the schema.
